#ifndef KEY_VERIFICATION_H_
#define KEY_VERIFICATION_H_

#include <Arduino.h>
#include <wolfssl.h>
#include <wolfssl/wolfcrypt/port/Espressif/esp32-crypt.h>
#include <wolfssl/wolfcrypt/random.h>
#include <wolfssl/wolfcrypt/ed25519.h>
#include <wolfssl/wolfcrypt/hpke.h>
#include <wolfssl/wolfcrypt/curve25519.h> // STOPSHIP

#include "door_sign_priv_key.h"

#define NONCE_SIZE 8

#define CHALLENGE_SIZE (NONCE_SIZE+ED25519_SIG_SIZE)

#define PUB_KEY_SIZE ED25519_PUB_KEY_SIZE

#define USER_DATA_SIZE 32
#define USER_ID_SIZE 8
#define PADDING_SIZE (USER_DATA_SIZE-USER_ID_SIZE)
#define PADDING_VALUE 0xAA
#define USER_SECRET_SIZE (USER_DATA_SIZE+ED25519_SIG_SIZE)
#define DECRYPTED_ACCESS_KEY_SIZE (NONCE_SIZE+USER_SECRET_SIZE)

#define EXCHANGE_INFO_LEN 14
byte EXCHANGE_INFO[] = "thecoven.space";


// STOPSHIP don't use hard-coded key!!
// byte TEST_PRIV_KEY[32] = {
//     0xd0, 0x13, 0x1a, 0xd0, 0xe6, 0x9e, 0x97, 0xfd, 0xc5, 0xea, 0x97, 0x87, 0x90, 0xf2, 0x13, 0x20,
//     0xbf, 0x1a, 0x89, 0xf2, 0xcb, 0x7b, 0x39, 0xa7, 0xe8, 0x45, 0x95, 0x69, 0x7a, 0xc4, 0xfa, 0x79,
// };
// byte TEST_PUB_KEY[32] = {
//     0x55, 0x80, 0xeb, 0x6a, 0x4d, 0x21, 0xe3, 0x41, 0xf8, 0x2f, 0x89, 0xb4, 0x41, 0xae, 0x22, 0xd1,
//     0x81, 0x14, 0xa1, 0x23, 0xc9, 0xe5, 0xc6, 0x4c, 0xac, 0x9a, 0xe6, 0xa6, 0x3d, 0x50, 0x60, 0x5f,
// };


class KeyVerification {
    public:
    WC_RNG kv_rng[1];
    ed25519_key server_pub_key;
    ed25519_key door_sign_key;
    
    Hpke hpke[1];
    void* skr = NULL;

    uint8_t nonce[NONCE_SIZE];
    uint8_t decryptedKey[256];

    int begin() {
        int ret = wolfCrypt_Init();
        if (ret != 0) {
            return ret;
        }

        ret = wc_InitRng(kv_rng);
        if (ret != 0) {
            return ret;
        }

        ret = wc_ed25519_import_private_key(DOOR_SIGN_PRIV_KEY, ED25519_PRV_KEY_SIZE,
                NULL, 0, &door_sign_key);
        if (ret != 0) {
            return ret;
        }

        ret = wc_HpkeInit(hpke, DHKEM_X25519_HKDF_SHA256, HKDF_SHA256, HPKE_AES_128_GCM, NULL);
        if (ret != 0) {
            return ret;
        }

        return 0;
    }

    // generate a challenge, which is a 64-bit secure-random nonce followed
    // by a signature signed by door_sign_priv_key using ed25519. Signature is 64 bytes,
    // meaning challenge must be 8+64=72 bytes.
    int generateChallenge(uint8_t* challenge) {
        int ret = wc_RNG_GenerateBlock(kv_rng, nonce, NONCE_SIZE);
        if (ret != 0) return ret;

        memcpy(challenge, nonce, NONCE_SIZE);

        unsigned int outLen = ED25519_SIG_SIZE;
        ret = wc_ed25519_sign_msg(challenge, NONCE_SIZE,
            challenge+NONCE_SIZE, &outLen, &door_sign_key);
        if (ret != 0) return ret;
        return 0;
    }

    // Generate pkRm, the serialized receiver public key.
    // The sender needs this key in order to seal the message.
    int getEncryptionPublicKey(uint8_t* output, uint16_t* outLen) {
        int ret = wc_HpkeGenerateKeyPair(hpke, &skr, kv_rng);
        if (ret != 0) return ret;

        // STOPSHIP overwrite with manual bytes
        // ret = wc_curve25519_import_private_raw_ex(TEST_PRIV_KEY, 32, TEST_PUB_KEY, 32, (curve25519_key*) skr, EC25519_LITTLE_ENDIAN);
        // if (ret != 0) return ret;

        uint32_t printSize = 32;
        ret = wc_curve25519_export_key_raw_ex((curve25519_key*) skr, decryptedKey, &printSize, decryptedKey+32, &printSize, EC25519_BIG_ENDIAN /*EC25519_LITTLE_ENDIAN*/);

        if (ret != 0) return ret;

        uint16_t pkr_size = PUB_KEY_SIZE;
        ret = wc_HpkeSerializePublicKey(hpke, skr, output, &pkr_size);
        if (ret != 0) return ret;
        *outLen = pkr_size;

        return 0;
    }

    // Verify the UserSecret was actually generated by the server, using the server's public key
    int verifyServerSignature(uint8_t* message, uint32_t messageLen, uint8_t* signature, uint32_t signatureLen) {
        int res;
        int verified;
        res = wc_ed25519_verify_msg(signature, signatureLen, message, messageLen, &verified, &server_pub_key);
        if (res != 0) return res;
        if (verified == 0) return 30; // invalid signature
        return 0; // ok
    }

    // Given an access key [CipherText+EncapsulationKey], decode the message
    // into UserSecret, and verify it is valid and signed by the server.
    // returns negative numbers for wolfssl errors, positive numbers for invalid key errors. 0 for valid.
    int verifyAccessKey(uint8_t* accessKey, size_t accessKeyLen, uint8_t* enc) {
        int res;
        res = wc_HpkeOpenBase(hpke, skr,
            enc, PUB_KEY_SIZE,
            EXCHANGE_INFO, EXCHANGE_INFO_LEN, // info
            NULL, 0, // aar
            accessKey, accessKeyLen,
            decryptedKey);
        // NOTE: for some reason this returns AES_GCM_AUTH_E, probably
        // because we aren't using mode_auth?
        if (res != 0 && res != AES_GCM_AUTH_E) return res;
        
        // nonce is first 8 bytes
        if (memcmp(decryptedKey, nonce, NONCE_SIZE) != 0) {
            return 10; // invalid nonce
        }
        uint8_t* userSecret = decryptedKey+NONCE_SIZE;
        // userId is the next 8 bytes
        // then 24 bytes of padding 0xAA
        uint8_t* padding = userSecret + USER_ID_SIZE;
        for (size_t i = 0; i < PADDING_SIZE; i++) {
            if (padding[i] != PADDING_VALUE) return 20; // invalid UserSecret
        }
        // server signature is the remaining 64 bytes
        uint8_t* serverSig = userSecret + USER_DATA_SIZE;
        res = verifyServerSignature(userSecret, USER_DATA_SIZE, serverSig, ED25519_SIG_SIZE);
        if (res != 0) return res;
        return 0;
    }

    void free() {
        if (skr != NULL)
            wc_HpkeFreeKey(hpke, hpke->kem, skr, NULL);
        wc_rng_free(kv_rng);
    }
};

#endif // KEY_VERIFICATION_H_
